#!/usr/bin/bash

set -e

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
source "${SCRIPT_DIR}/common" 

INSTANCE_NAME=${1:-cluster01}

echo "Creating: $INSTANCE_NAME"

test -f "$SCRIPT_DIR/config" || die "File 'config' is missing. You didn't read the docs, did you?"
set -a
source "$SCRIPT_DIR/config"
set +a

: ${DEVELOPER_PASSWORD:=developer}
export DEVELOPER_PASSWORD

test -n "$SSH_KEY_NAME" || die "'SSH_KEY_NAME' is not configured"
test -n "$SERVER_TYPE" || die "'SERVER_TYPE' is not configured"
test -n "$PRIVATE_KEY_BASE" || echo "'PRIVATE_KEY_BASE' is not configured, fallback to self-signed setup."

if [ -n "$BASE_DOMAIN" ]; then
	PUBLIC_NAME="${INSTANCE_NAME}${SUB_DOMAIN_PART:+.}${SUB_DOMAIN_PART}.${BASE_DOMAIN}"
fi
echo "Using DNS name: $PUBLIC_NAME"

export PRIVATE_KEY_BASE
export PUBLIC_NAME

envsubst < cloud-config.yaml.in | hcloud server create --ssh-key "$SSH_KEY_NAME" --datacenter "$DATACENTER" --image centos-7 --type "$SERVER_TYPE" --name "$INSTANCE_NAME" --user-data-from-file -

echo
echo "Developer credentials: developer / $DEVELOPER_PASSWORD"
if [ -n "$ADMIN_PASSWORD" ]; then
	echo "Admin credentials: admin / $ADMIN_PASSWORD"
fi
echo

if [ -n "$BASE_DOMAIN" ]; then
	$SCRIPT_DIR/update-dns "$INSTANCE_NAME"
fi
