#!/usr/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
source "${SCRIPT_DIR}/common" 

test -f "$SCRIPT_DIR/config" || die "File 'config' is missing. You didn't read the docs, did you?"
set -a
source "$SCRIPT_DIR/config"
set +a

INSTANCE_NAME=${1:-cluster01}

PUBLIC_NAME="${INSTANCE_NAME}${SUB_DOMAIN_PART:+.}${SUB_DOMAIN_PART}.${BASE_DOMAIN}"
PUBLIC_IP="$(hcloud_ipv4_server "$INSTANCE_NAME")"

echo "Using DNS name: $PUBLIC_NAME"
echo "Using IP: $PUBLIC_IP"

$SCRIPT_DIR/dns/set_dns_record.${DNS_MODE:-lexicon} "$INSTANCE_NAME" "$SUB_DOMAIN_PART" "$BASE_DOMAIN" "$PUBLIC_IP"

echo "DNS updated:"
echo "     ${PUBLIC_NAME}   A   $PUBLIC_IP"
echo "   *.${PUBLIC_NAME}   A   $PUBLIC_IP"
